---
# performYumUpdateRebootServer.yaml
# performs yum update and reboots server
- name: perform yum update / reboot server
  hosts: webservers
  remote_user: root
  become: true

 
  tasks:
        - name: Perform yum update of all packages
          yum:
            name: '*'
            state: latest
        - name: Reboot server
          command: /sbin/shutdown -r +1
          ignore_errors: true